version: '3.8'

services:
  db:
    image: postgres:15
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_CONTAINTER_NAME}